name: Bingo
version: "0.0.1"
author: Swung0x48 & Ghomist & Xenapte
main: info.bcrc.mc.bingo.Bingo
api-version: 1.17
commands:
  bingo:
    description: controls Bingo actions
    usage: /bingo <setup|join|start|exitworld>
    permission: bingo.permission
    permission-message: You don't have the permission to run this command!
